version: '3.7'
services:
  api:
    container_name: backend-note-api
    image: lehuuson/backend-note:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - note-db-network
      - note-redis-network
    depends_on:
      - redis
      - mongodb
  redis:
    container_name: note-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./dockers/data/db/redis:/data
    networks:
      - note-redis-network
    user: "999:1000"
  mongodb:
    image: mongo:4.2.3-bionic
    container_name: note-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=note
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./dockers/data/db/mongo:/data/db
    networks:
      - note-db-network
    user: "999:999"
networks:
  note-db-network:
    driver: bridge
  note-redis-network:
    driver: bridge
